### ISSUE TITLE
new way to use nimfa.mf in version 1.2.1?

### ISSUE THREAD

**Issue by ccshao** [marinkaz/nimfa#20]
Previous it is possible to use different nmf methods by nimfa.mf interface, like following: 

import nimfa
import numpy as np
V = np.random.random((10000, 1000))
fctr = nimfa.mf(V, seed = 'random_vcol', method = 'lsnmf', rank = 40, max_iter = 50)
fctr_res = nimfa.mf_run(fctr)

Now it gives the error:
**AttributeError: 'module' object has no attribute 'mf'**

What is the proper way to use different method through a common interface ?

**Comment by marinkaz** [comment]
Please see documentation and examples at http://nimfa.biolab.si. There you will find examples of how to use different NMF algorithms. 

Briefly, with nimfa 1.2.1. the API has changed. Instead of having to specify the variant of NMF algorithm via string parameter (e.g. nimfa.mf(method='lsnmf')), you should now call it in the following way (here is a working example):

```
import nimfa
V = nimfa.examples.medulloblastoma.read(normalize=True)

lsnmf = nimfa.Lsnmf(V, seed='random_vcol', rank=50, max_iter=100)
lsnmf_fit = lsnmf()

print('Rss: %5.4f' % lsnmf_fit.fit.rss())
print('Evar: %5.4f' % lsnmf_fit.fit.evar())
print('K-L divergence: %5.4f' % lsnmf_fit.distance(metric='kl'))
print('Sparseness, W: %5.4f, H: %5.4f' % lsnmf_fit.fit.sparseness())
```

**Comment by ccshao** [comment]
Thanks for the examples. However, the old way of calling of NMF algorithms are actually easier to use. 
For example, if I want to compare performance of multiple algorithms, I could just use nimfa.mf(method = METHOD), while change METOHD accordingly. 

In the new version, I have to use nimfa.Nmf(),  nimfa.Bd, etc, which is not as feasible as before. 

I feel it will be nicer if the wrap function is preserved.

**Comment by marinkaz** [comment]
Let's say you would like to run three NMF variants: the standard NMF, BD and LSNM. 

In Nimfa 1.0 we would run these three variants using the following pseudocode:

```
methods = ['nmf', 'bd', 'lsnmf']
for method in methods:
	nimfa.mf(V, ..., method=method)
```

In Nimfa 1.2 we would run these three variants in the following manner:

```
methods = [nimfa.Nmf, nimfa.Bd, nimfa.Lsnmf]
for method in methods:
    method(V, ...)
```

In this way, no extra lines of code are needed. Also, you can call the NMF variant by using auto completion (say, in IPython) instead of having to specify the method by its string name. However, you made a good point; we might include the wrap function back into Nimfa.
